defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

data_paths:
  - data/arc-aug-1000

checkpoint_path: checkpoints/trm_teacher.ckpt
output_dir: planner_outputs/arc1
global_batch_size: 128
seed: 0
limit_batches:

planner:
  beam_size: 4
  max_steps: 16
  max_nodes_per_beam: 64
  score_alpha: 1.0
  score_beta: 0.0
  step_penalty: 0.01
  num_runs: 1
  top_k_per_puzzle: 1
  noise_std: 0.0
